# https://taskfile.dev

version: "3"
silent: true

tasks:
  default:
    cmds:
      - go run . {{.CLI_ARGS}}
    interactive: true
    desc: Run gh-wt

  debug:
    cmds:
      - DEBUG=true go run . --debug {{.CLI_ARGS}}
    interactive: true
    desc: Run in debug mode

  fmt:
    desc: Run gofumpt
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix
    env:
      GOEXPERIMENT: null

  lint:
    desc: Run linters
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m
    env:
      GOEXPERIMENT: null

  lint-fix:
    desc: Run linters and fix issues
    cmds:
      - golangci-lint run --path-mode=abs --config=".golangci.yml" --timeout=5m --fix
    env:
      GOEXPERIMENT: null

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  build:
    desc: Build the extension binary
    vars:
      VERSION:
        sh: git describe --tags --dirty --always 2>/dev/null | sed 's/^v//' || echo "dev"
    cmds:
      - go build -ldflags "-X=github.com/ffalor/gh-wt/cmd.Version={{.VERSION}}" -o gh-wt

  clean:
    desc: Remove built binary and dist
    cmds:
      - rm -f gh-wt
      - rm -rf dist

  install:
    desc: Install the gh extension locally
    cmds:
      - gh extension install . --force

  remove:
    desc: Remove the gh extension
    ignore_error: true
    cmds:
      - gh extension remove wt
